import Mathlib

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

namespace Problems.Minif2f.algebra_3rootspoly_amdtamctambeqnasqmbpctapcbtdpasqmbpctapcbta

end Problems.Minif2f.algebra_3rootspoly_amdtamctambeqnasqmbpctapcbtdpasqmbpctapcbta
