import Mathlib
import Problems.Topology.brouwer_fixed_point.Defs
import Problems.Topology.brouwer_fixed_point.proofs.L_span_preimage_eq_top
import Problems.Topology.brouwer_fixed_point.proofs.L_subspace_preimage_props

namespace Problems.Topology.brouwer_fixed_point

-- Pick concrete witness V := Submodule.span ℝ K' and T := (V.subtype) ⁻¹' K'.
-- sub_1 (`subspace_preimage_props`): generic in V — given K' ⊆ ↑V, the lifted
--   preimage in V is nonempty/compact/convex/0∈T, with K' ≃ₜ T (uses only the
--   inclusion V → E being a topological embedding + Subtype.val linear).
-- sub_2 (`span_preimage_eq_top`): the lifted preimage spans the whole subspace
--   when V = Submodule.span ℝ K' (this is the algebraic content of "the
--   subspace generated by K' is exactly its span").
-- Each sub-goal is strictly simpler: sub_1 drops the existential and the span
--   condition; sub_2 is purely a Submodule identity with no topology.
theorem s10817
    {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] {K' : Set E}
    (hne : K'.Nonempty) (hcomp : IsCompact K') (hconv : Convex ℝ K')
    (h0 : (0 : E) ∈ K') :
    ∃ (V : Submodule ℝ E) (T : Set V),
      T.Nonempty ∧ IsCompact T ∧ Convex ℝ T ∧
      (0 : V) ∈ T ∧ Submodule.span ℝ T = ⊤ ∧
      Nonempty (K' ≃ₜ T)  := by
  set V : Submodule ℝ E := Submodule.span ℝ K' with hV
  set T : Set V := (Subtype.val : V → E) ⁻¹' K' with hT
  have h_props : T.Nonempty ∧ IsCompact T ∧ Convex ℝ T ∧ (0 : V) ∈ T ∧
      Nonempty (K' ≃ₜ T) :=
    subspace_preimage_props V Submodule.subset_span hne hcomp hconv h0
  have h_span : Submodule.span ℝ T = ⊤ := span_preimage_eq_top (K' := K')
  exact ⟨V, T, h_props.1, h_props.2.1, h_props.2.2.1, h_props.2.2.2.1, h_span,
    h_props.2.2.2.2⟩
end Problems.Topology.brouwer_fixed_point
