-- Pick concrete witness V := Submodule.span ℝ K' and T := (V.subtype) ⁻¹' K'.
-- sub_1 (`subspace_preimage_props`): generic in V — given K' ⊆ ↑V, the lifted
--   preimage in V is nonempty/compact/convex/0∈T, with K' ≃ₜ T (uses only the
--   inclusion V → E being a topological embedding + Subtype.val linear).
-- sub_2 (`span_preimage_eq_top`): the lifted preimage spans the whole subspace
--   when V = Submodule.span ℝ K' (this is the algebraic content of "the
--   subspace generated by K' is exactly its span").
-- Each sub-goal is strictly simpler: sub_1 drops the existential and the span
--   condition; sub_2 is purely a Submodule identity with no topology.
import Mathlib
import Problems.Topology.brouwer_fixed_point.Defs
import Problems.Topology.brouwer_fixed_point.proofs._strategy_s10817

namespace Problems.Topology.brouwer_fixed_point

def embed_into_span_submodule := @Problems.Topology.brouwer_fixed_point.s10817

end Problems.Topology.brouwer_fixed_point
