"""Builder pipeline (P2).

stages: tactic_try → failure_replay → find_lemmas → tactic_llm → self_verify → commit

tactic_try hardcoded list: [rfl, simp, decide, norm_num, ring]
  - pass → commit directly (skip tactic_llm)
  - exhausted → write dead_attempts → move to failure_replay + tactic_llm loop

failure_replay: reads dead_attempts from DB (target=strategy, K_digest=5, newest first)

find_lemmas: stub — returns empty list (P3 search subsystem)

tactic_llm (agent stage): dispatches to one of three outcomes:
  a) tactic_proof   → self_verify (single file) → proved | retry
  b) needs_decomp   → early exit
  c) bad_goal       → write dead_attempts + early exit

self_verify (single file): lake build staging .lean — outcome MUST be 'proved'.
  Silent-failure guard: any outcome other than 'proved' (error, timeout, hasSorry)
  returns False and triggers retry from tactic_llm.

T_wall enforcement: preserved from P1.
"""
from __future__ import annotations

import json
import re
import time
import uuid
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
import sqlite3

from Tooling.commit import CommitWriter
from Tooling.lake import run_lean
from Tooling.agent.provider import AgentResponse, FallbackChain, ModelResolver


TACTICS: list[str] = ["rfl", "simp", "decide", "norm_num", "ring"]
DEFAULT_T_WALL: float = 30 * 60.0
K_DIGEST: int = 5


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _row_as_dict(conn: sqlite3.Connection, table: str, row_id: int) -> dict[str, Any]:
    cur = conn.execute(f"SELECT * FROM {table} WHERE id = ?", (row_id,))
    row = cur.fetchone()
    if row is None:
        raise ValueError(f"{table} row {row_id} not found")
    return dict(zip([d[0] for d in cur.description], row))


def _replace_proof_body(content: str, tactic: str) -> str:
    """Replace proof body (everything from the last ':=') with 'by TACTIC'.

    P1 simplification: rfind(':=') is safe for P1 demo theorems (no `let x :=`
    inside proof, no `arg : T := default`). P2+ strategy files generated by
    tactic_llm may contain nested `:=` (e.g. `by exact (let x := 5; x)` or
    `have : Q := q1; ...`); a strict Lean parser or staging template marking
    the proof-body start position is required there.
    """
    idx = content.rfind(":=")
    if idx == -1:
        return content
    return content[:idx] + f":= by {tactic}"


@dataclass
class BuilderConfig:
    t_wall: float = DEFAULT_T_WALL
    lake_timeout: float = 600.0
    base_dir: str = "."
    k_digest: int = K_DIGEST
    max_retries: int = 3  # tactic_llm + self_verify retry cap


@dataclass
class BuilderResult:
    outcome: str  # "proved" | "exhausted" | "needs_decomp" | "bad_goal"
    tactic: str | None = None
    timed_out: bool = False


class Builder:
    def __init__(
        self,
        strategy_id: int,
        conn: sqlite3.Connection,
        config: BuilderConfig | None = None,
        chain: FallbackChain | None = None,
        resolver: ModelResolver | None = None,
    ) -> None:
        self.strategy_id = strategy_id
        self.conn = conn
        self.config = config or BuilderConfig()
        self.chain = chain
        self.resolver = resolver or ModelResolver()
        self._writer = CommitWriter(conn)
        self._start: float = 0.0

    def _resolve_path(self, lean_path: str) -> Path:
        """Resolve lean_path against base_dir if not absolute.

        CLI stores paths relative to the workspace root (e.g. Problems/ex/...).
        In-process calls where CWD != base_dir need this resolution; subprocess
        calls already run with CWD=workspace so both absolute and relative work.
        """
        p = Path(lean_path)
        if not p.is_absolute():
            return Path(self.config.base_dir) / p
        return p

    # ------------------------------------------------------------------
    # Stage: failure_replay — read dead_attempts from DB
    # ------------------------------------------------------------------

    def _failure_replay(self) -> list[dict]:
        """Read up to K_digest most recent dead_attempts for this strategy."""
        rows = self.conn.execute(
            "SELECT reason_summary, outcome, ts FROM dead_attempts "
            "WHERE target_id = ? AND target_kind = 'Strategy' "
            "ORDER BY ts DESC LIMIT ?",
            (str(self.strategy_id), self.config.k_digest),
        ).fetchall()
        return [{"reason": r[0], "outcome": r[1], "ts": r[2]} for r in rows]

    # ------------------------------------------------------------------
    # Stage: find_lemmas (stub — P3 search subsystem)
    # ------------------------------------------------------------------

    def _find_lemmas(self, goal: dict) -> list[str]:
        return []

    # ------------------------------------------------------------------
    # Stage: tactic_llm (agent)
    # ------------------------------------------------------------------

    def _load_prompt_template(self) -> str:
        prompt_path = (
            Path(__file__).parents[2] / "docs" / "prompts" / "builder_tactic_llm.md"
        )
        return prompt_path.read_text(encoding="utf-8")

    def _build_prompt(
        self, goal: dict, dead_attempts: list[dict], lemmas: list[str]
    ) -> str:
        template = self._load_prompt_template()
        dead_str = json.dumps(dead_attempts, indent=2) if dead_attempts else "[]"
        lemmas_str = "\n".join(f"- {lem}" for lem in lemmas) if lemmas else "(none)"
        return (
            template
            .replace("{{GOAL_PROBLEM}}", goal.get("problem") or "")
            .replace("{{GOAL_SLUG}}", goal.get("slug") or "")
            .replace("{{GOAL_STATEMENT}}", goal.get("question") or "")
            .replace("{{DEAD_ATTEMPTS}}", dead_str)
            .replace("{{CANDIDATE_LEMMAS}}", lemmas_str)
        )

    def _run_tactic_llm(
        self,
        goal: dict,
        dead_attempts: list[dict],
        lemmas: list[str],
        session_id: str,
        staging_dir: str,
    ) -> AgentResponse | None:
        assert self.chain is not None
        model_tier = self.resolver.resolve("builder", "tactic_llm")
        prompt = self._build_prompt(goal, dead_attempts, lemmas)
        response, outcome = self.chain.run(
            model_tier=model_tier,
            prompt=prompt,
            scope_dirs=[staging_dir],
            session_id=session_id,
            staging_dir=staging_dir,
        )
        return response if outcome == "success" else None

    def _parse_tactic_response(self, output: str) -> dict | None:
        """Parse agent JSON output. Returns None (→ retry) if:
          - no JSON code block and body is not parseable JSON
          - parsed value is not a dict
          - dict lacks all three expected keys
        """
        m = re.search(r'```(?:json)?\s*([\s\S]*?)```', output)
        text = m.group(1).strip() if m else output.strip()
        try:
            obj = json.loads(text)
        except json.JSONDecodeError:
            return None
        if not isinstance(obj, dict):
            return None
        valid_keys = {"tactic_proof", "needs_decomposition", "bad_goal"}
        if not (valid_keys & obj.keys()):
            return None
        return obj

    # ------------------------------------------------------------------
    # Stage: self_verify (single file)
    # ------------------------------------------------------------------

    def _self_verify(self, staging_path: Path, timeout: float) -> bool:
        """Verify staging file with lake. Returns True only if outcome == 'proved'.

        Silent-failure guard: any outcome other than 'proved' (elaboration error,
        timeout, hasSorry, or any other non-proved result) returns False and
        forces a retry from tactic_llm. Never silently pass an unverified proof.
        """
        result = run_lean(str(staging_path), self.config.base_dir, timeout)
        return result.outcome == "proved"

    # ------------------------------------------------------------------
    # bad_goal: write dead_attempts for this goal + parent goal
    # ------------------------------------------------------------------

    def _record_bad_goal(
        self, goal: dict, pipeline_id: str, reason: str
    ) -> None:
        now = _now()
        goal_id = goal["id"]
        with self.conn:
            self.conn.execute(
                "INSERT INTO dead_attempts "
                "(target_id, target_kind, pipeline_id, pipeline_kind, "
                "outcome, reason_summary, ts) VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    str(goal_id), "Goal", pipeline_id, "Builder",
                    "bad_goal", f"Builder reviewed bad: {reason}", now,
                ),
            )
        # Best-effort: find parent goal via strategy_subgoals and record there too
        parent_row = self.conn.execute(
            "SELECT s.goal_id FROM strategies s "
            "JOIN strategy_subgoals ss ON ss.strategy_id = s.id "
            "WHERE ss.subgoal_id = ?",
            (goal_id,),
        ).fetchone()
        if parent_row is not None:
            parent_goal_id = parent_row[0]
            with self.conn:
                self.conn.execute(
                    "INSERT INTO dead_attempts "
                    "(target_id, target_kind, pipeline_id, pipeline_kind, "
                    "outcome, reason_summary, ts) VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (
                        str(parent_goal_id), "Goal", pipeline_id, "Builder",
                        "bad_goal",
                        f"prior decomp produced bad sub-Goal {goal_id}: {reason}",
                        now,
                    ),
                )

    # ------------------------------------------------------------------
    # tactic_llm loop (stages 4+5 with retry)
    # ------------------------------------------------------------------

    def _tactic_llm_loop(
        self,
        strategy: dict[str, Any],
        goal: dict[str, Any],
        pipeline_id: str,
        staging_dir: Path,
        session_id: str,
        dead_attempts: list[dict],
        lemmas: list[str],
        source_content: str,
    ) -> BuilderResult:
        for _attempt in range(self.config.max_retries):
            elapsed = time.monotonic() - self._start
            if elapsed >= self.config.t_wall:
                return BuilderResult(outcome="exhausted", timed_out=True)

            response = self._run_tactic_llm(
                goal, dead_attempts, lemmas, session_id, str(staging_dir)
            )
            if response is None:
                # chain exhausted (all providers/retries failed)
                return BuilderResult(outcome="exhausted")

            parsed = self._parse_tactic_response(response.output)
            if parsed is None:
                # malformed JSON → retry agent
                continue

            if "needs_decomposition" in parsed:
                return BuilderResult(outcome="needs_decomp")

            if "bad_goal" in parsed:
                reason = str(parsed.get("bad_goal") or "")
                self._record_bad_goal(goal, pipeline_id, reason)
                return BuilderResult(outcome="bad_goal")

            if "tactic_proof" in parsed:
                tactic_code = str(parsed["tactic_proof"])
                staging_lean = staging_dir / "tactic_llm.lean"
                staging_lean.write_text(
                    _replace_proof_body(source_content, tactic_code),
                    encoding="utf-8",
                )

                elapsed = time.monotonic() - self._start
                if elapsed >= self.config.t_wall:
                    return BuilderResult(outcome="exhausted", timed_out=True)

                remaining = self.config.t_wall - elapsed
                per_call_timeout = min(self.config.lake_timeout, remaining)

                # Stage 5: self_verify — MUST return proved; anything else retries
                if self._self_verify(staging_lean, per_call_timeout):
                    self._commit_success(strategy, staging_lean)
                    return BuilderResult(outcome="proved", tactic=tactic_code)
                # self_verify failed → retry from tactic_llm (spec §1 step 5)

        return BuilderResult(outcome="exhausted")

    # ------------------------------------------------------------------
    # Main orchestration
    # ------------------------------------------------------------------

    def run(self) -> BuilderResult:
        self._start = time.monotonic()
        p_uuid = str(uuid.uuid4())

        strategy = _row_as_dict(self.conn, "strategies", self.strategy_id)
        goal = _row_as_dict(self.conn, "goals", strategy["goal_id"])

        pipeline_id = self._insert_pipeline(p_uuid)
        staging_dir = self._staging_dir(goal, p_uuid)
        staging_dir.mkdir(parents=True, exist_ok=True)

        source_content = self._resolve_path(strategy["lean_path"]).read_text(
            encoding="utf-8"
        )

        result = self._run_all_stages(
            strategy, goal, pipeline_id, staging_dir, source_content
        )

        self._finish_pipeline(pipeline_id, result.outcome)
        self._emit_event(
            "pipeline_finished",
            {
                "pipeline_id": pipeline_id,
                "strategy_id": self.strategy_id,
                "outcome": result.outcome,
            },
        )
        return result

    def _run_all_stages(
        self,
        strategy: dict[str, Any],
        goal: dict[str, Any],
        pipeline_id: str,
        staging_dir: Path,
        source_content: str,
    ) -> BuilderResult:
        """Execute all stages; returns BuilderResult.
        Caller is responsible for _finish_pipeline + _emit_event.
        """
        tactic_dead: list[dict[str, Any]] = []
        timed_out = False
        proved_tactic: str | None = None
        proved_staging: Path | None = None

        # Stage 1: tactic_try
        for tactic in TACTICS:
            elapsed = time.monotonic() - self._start
            if elapsed >= self.config.t_wall:
                timed_out = True
                break
            remaining = self.config.t_wall - elapsed
            per_call_timeout = min(self.config.lake_timeout, remaining)

            staging_lean = staging_dir / f"attempt_{tactic}.lean"
            staging_lean.write_text(
                _replace_proof_body(source_content, tactic), encoding="utf-8"
            )

            lake_result = run_lean(
                str(staging_lean),
                self.config.base_dir,
                timeout=per_call_timeout,
            )

            if lake_result.outcome == "proved":
                proved_tactic = tactic
                proved_staging = staging_lean
                break
            else:
                tactic_dead.append(
                    {
                        "tactic": tactic,
                        "timed_out": lake_result.timed_out,
                        "messages": lake_result.messages,
                    }
                )

        if proved_tactic and proved_staging:
            # tactic_try pass → commit directly; no tactic_llm needed
            self._commit_success(strategy, proved_staging)
            return BuilderResult(outcome="proved", tactic=proved_tactic)

        # Record dead_attempts for tactic_try failures (whether T_wall or exhausted)
        self._record_dead_attempts(tactic_dead, pipeline_id)

        if timed_out:
            return BuilderResult(outcome="exhausted", timed_out=True)

        # No agent chain → P1 fallback (tactic_try only)
        if self.chain is None:
            return BuilderResult(outcome="exhausted")

        # Stage 2: failure_replay (reads dead_attempts including tactic_try just written)
        dead_attempts = self._failure_replay()

        # Stage 3: find_lemmas (stub)
        lemmas = self._find_lemmas(goal)

        # Stages 4+5: tactic_llm + self_verify retry loop
        session_id = str(uuid.uuid4())
        return self._tactic_llm_loop(
            strategy,
            goal,
            pipeline_id,
            staging_dir,
            session_id,
            dead_attempts,
            lemmas,
            source_content,
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _staging_dir(self, goal: dict[str, Any], p_uuid: str) -> Path:
        base = Path(self.config.base_dir)
        g_folder = f"{goal['id']}_{goal['slug']}"
        return base / "Problems" / goal["problem"] / "Goals" / g_folder / "Staging" / p_uuid

    def _insert_pipeline(self, p_uuid: str) -> str:
        with self.conn:
            self.conn.execute(
                "INSERT INTO pipelines "
                "(id, kind, runtime, target_id, target_kind, status, started_at) "
                "VALUES (?, ?, ?, ?, ?, ?, ?)",
                (
                    p_uuid, "Builder", "atomic",
                    str(self.strategy_id), "Strategy",
                    "running", _now(),
                ),
            )
        return p_uuid

    def _finish_pipeline(self, pipeline_id: str, outcome: str) -> None:
        status = "succeeded" if outcome == "proved" else "failed"
        with self.conn:
            self.conn.execute(
                "UPDATE pipelines SET status = ?, outcome = ?, finished_at = ? WHERE id = ?",
                (status, outcome, _now(), pipeline_id),
            )

    def _commit_success(self, strategy: dict[str, Any], staging_lean: Path) -> None:
        self._writer.begin("strategies", "update", row_id=self.strategy_id)
        self._writer.stage_file(staging_lean, self._resolve_path(strategy["lean_path"]))
        self._writer.finalize("strategies", self.strategy_id, {"status": "succeeded"})

    def _record_dead_attempts(
        self,
        dead: list[dict[str, Any]],
        pipeline_id: str,
    ) -> None:
        now = _now()
        with self.conn:
            for attempt in dead:
                msgs = attempt.get("messages", [])
                kind_hint = next((m.get("kind", "") for m in msgs if m.get("kind")), "")
                if attempt.get("timed_out"):
                    reason = f"tactic {attempt['tactic']}: timed_out"
                elif kind_hint:
                    reason = f"tactic {attempt['tactic']}: {kind_hint}"
                else:
                    reason = f"tactic {attempt['tactic']}: failed"
                self.conn.execute(
                    "INSERT INTO dead_attempts "
                    "(target_id, target_kind, pipeline_id, pipeline_kind, "
                    "outcome, reason_summary, ts) VALUES (?, ?, ?, ?, ?, ?, ?)",
                    (
                        str(self.strategy_id), "Strategy",
                        pipeline_id, "Builder",
                        "exhausted", reason, now,
                    ),
                )

    def _emit_event(self, kind: str, payload: dict[str, Any]) -> None:
        with self.conn:
            self.conn.execute(
                "INSERT INTO events (kind, payload, ts) VALUES (?, ?, ?)",
                (kind, json.dumps(payload), _now()),
            )
