import Mathlib

set_option maxHeartbeats 0

open BigOperators Real Nat Topology Rat

namespace Problems.Minif2f.algebra_xmysqpymzsqpzmxsqeqxyz_xpypzp6dvdx3y3z3

end Problems.Minif2f.algebra_xmysqpymzsqpzmxsqeqxyz_xpypzp6dvdx3y3z3
