"""Library promotion: re-export proved roots into Library/<Topic>/.

When a Problem's root goal flips to status='proved', this module:

  1. Verifies its `#print axioms` set is a subset of the Manifest's
     `axioms_whitelist`. Reject otherwise (no promotion of unverified
     proofs).
  2. Picks a topic from the Manifest's lemma_hints (first
     `Library.<Topic>.*` entry, fallback `Misc`).
  3. Writes `Library/<Topic>/<problem>.lean` containing a re-export of
     `Problems.<problem>.main` under the Library namespace.
  4. Appends a one-line entry to `Library/<Topic>/INDEX.md`.

Idempotent: a second call after success is a no-op (file exists +
INDEX entry already present). Cascade always tries; if Library state
already correct the function returns False to indicate no work done.

Topic list mirrors Mathlib's first-level dirs (see Library/README.md).
Unknown topics from lemma_hints are honored as-is — agents can extend
the topic set without code changes.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

from . import db, manifest
from .pipeline._axiom import axiom_probe


# Topic recognized by the framework; informational only (we don't
# reject unknown topics). Matches Library/README.md's enumeration.
KNOWN_TOPICS = (
    "Algebra", "Analysis", "Combinatorics", "Data", "Geometry",
    "Logic", "MeasureTheory", "NumberTheory", "Order", "SetTheory",
    "Topology", "CategoryTheory", "Misc",
)

_LIBRARY_HINT_RE = re.compile(r"^Library\.([A-Za-z][A-Za-z0-9_]*)\.")


def topic_from_hints(hints: list[str]) -> str:
    """Pick the topic for promotion. First Library.<Topic>.* hint wins;
    fallback to 'Misc' so promotion always has a destination."""
    for h in hints:
        m = _LIBRARY_HINT_RE.match(h)
        if m:
            return m.group(1)
    return "Misc"


def topics_from_hints(hints: list[str]) -> list[str]:
    """All distinct Library.<Topic>.* topics in hints (preserves order).
    Used to filter which Library/<Topic>/INDEX.md entries the agent
    sees in Context.md."""
    seen: set[str] = set()
    out: list[str] = []
    for h in hints:
        m = _LIBRARY_HINT_RE.match(h)
        if m and m.group(1) not in seen:
            seen.add(m.group(1))
            out.append(m.group(1))
    return out


def _re_export_content(problem: str) -> str:
    """Lean source for `Library/<Topic>/<problem>.lean`. Re-exports
    `Problems.<problem>.main` so callers can `import Library.<Topic>.
    <problem>` and use `<problem>` as the theorem name."""
    return (
        f"import Problems.{problem}.Root\n"
        f"\n"
        f"-- auto-generated by Asterism Library promotion. Do not\n"
        f"-- edit; the next promotion of this Problem will overwrite.\n"
        f"\n"
        f"theorem {problem} := Problems.{problem}.main\n"
    )


def _index_entry(problem: str, statement: str) -> str:
    """One-line INDEX.md entry. statement may span lines; collapse +
    truncate to keep INDEX scannable."""
    one_line = " ".join(statement.split())
    if len(one_line) > 240:
        one_line = one_line[:237] + "..."
    return f"- `{problem}` — {one_line}"


def promote(workspace: Path, problem: str,
            mfst: manifest.Manifest, root_statement: str) -> tuple[bool, str]:
    """Run a single promotion attempt. Returns (promoted, message).
    `promoted=False` covers idempotent skip and axiom-gate reject;
    callers log message either way."""
    topic = topic_from_hints(mfst.all_hints)
    topic_dir = workspace / "Library" / topic
    target = topic_dir / f"{problem}.lean"
    desired = _re_export_content(problem)
    needle = f"- `{problem}`"
    index = topic_dir / "INDEX.md"
    desired_entry = _index_entry(problem, root_statement)

    # Idempotence short-circuit: if the Library re-export already exists
    # with the exact content we'd write AND INDEX.md already lists this
    # problem with the current statement, this run was promoted in a
    # prior tick — skip the axiom_probe (~3-5s of gateway work). Under
    # per-problem gating in the dispatcher this path is hit on every
    # subsequent tick for already-promoted problems, so it must not pay
    # axiom-probe cost. Statement-edit case is not short-circuited so
    # INDEX gets the fresh entry. Edge case (manual rewrite of Library/
    # files between ticks) is accepted: the framework owns these files
    # during a run.
    if target.exists() and target.read_text(encoding="utf-8") == desired \
            and index.exists():
        for ln in index.read_text(encoding="utf-8").splitlines():
            if ln.strip().startswith(needle):
                if ln.strip() == desired_entry:
                    return False, (f"[library] {problem}: already "
                                   f"promoted in {topic}/ "
                                   f"(idempotent skip)")
                break

    # Empty whitelist = accept (legacy behavior, matches manifests
    # without an `axioms_whitelist:` field). Skip the probe entirely
    # in that case so we don't pay lake build time.
    if not mfst.axioms_whitelist:
        axiom_msg = "(no whitelist; accepting any axioms)"
    else:
        # Use the shared axiom_probe — it does `lake build <module>`
        # first to defeat the stale-olean cache, which the prior
        # local impl missed. Library promotion is the last gate
        # before a proved root is re-exported into the shared
        # Library/, so a false-positive accept here would publish a
        # sorry-tainted theorem network-wide.
        ok, axiom_msg = axiom_probe(
            workspace,
            fq_name=f"Problems.{problem}.main",
            module=f"Problems.{problem}.Root",
            whitelist=mfst.axioms_whitelist,
        )
        if not ok:
            return False, f"[library] {problem}: skip — {axiom_msg}"

    topic_dir.mkdir(parents=True, exist_ok=True)
    file_was_dirty = (
        not target.exists()
        or target.read_text(encoding="utf-8") != desired
    )
    if file_was_dirty:
        target.write_text(desired, encoding="utf-8")

    entry = desired_entry
    if index.exists():
        body = index.read_text(encoding="utf-8")
    else:
        body = f"# Library/{topic} — INDEX\n\n"
    existing_lines = body.splitlines()
    has_entry = any(ln.strip().startswith(needle) for ln in existing_lines)
    new_lines = []
    if has_entry:
        for ln in existing_lines:
            if ln.strip().startswith(needle):
                new_lines.append(entry)
            else:
                new_lines.append(ln)
    else:
        new_lines = list(existing_lines)
        if new_lines and new_lines[-1] != "":
            new_lines.append("")  # spacer when extending past header
        new_lines.append(entry)
    new_body = "\n".join(new_lines)
    if not new_body.endswith("\n"):
        new_body += "\n"
    index_was_dirty = new_body != body
    if index_was_dirty:
        index.write_text(new_body, encoding="utf-8")

    if not file_was_dirty and not index_was_dirty:
        return False, f"[library] {problem}: already up-to-date in {topic}/"
    return True, f"[library] promoted {problem} → Library/{topic}/ ({axiom_msg})"


def maybe_promote(conn, workspace: Path, problem: str,
                  mfst: manifest.Manifest) -> None:
    """Cascade hook: called whenever any Goal in `problem` flips to
    'proved'. No-ops unless the root is proved. Logs result of each
    attempt to stdout (`[library] ...`); never raises.

    Also acts as the single integrity gate under verify-collapse:
    per-level cascade promotes are mechanical (no Lean elaboration);
    `axiom_probe(Root.lean)` here is the actual proof validation.
    On rogue-axiom failure (sorryAx in a non-leaf strategy patch)
    invokes `verify.bisect_sorryax_source` + `rollback_cascade_chain`
    to revert the cascade — framework cascade machinery will then
    re-Backward the culprit goal on the next dispatcher tick.
    """
    row = conn.execute(
        "SELECT statement FROM goals "
        "WHERE problem = ? AND origin = 'root' AND status = 'proved' "
        "LIMIT 1",
        (problem,),
    ).fetchone()
    if row is None:
        return
    try:
        promoted, msg = promote(workspace, problem, mfst,
                                str(row["statement"]))
        print(msg, flush=True)
        if not promoted and ("rogue axioms" in msg or "sorryAx" in msg):
            _handle_sorryax_at_root(conn, workspace, problem)
            return
        # Happy path: clean up cascade backups accumulated by
        # `verify_strategy` during cascade promotion.
        from . import verify as _verify
        n = _verify.cleanup_cascade_backups(conn, workspace, problem)
        if n:
            print(f"[library] {problem}: cleaned {n} cascade backup(s)",
                  flush=True)
    except Exception as e:
        print(f"[library] {problem}: promotion error ({e})",
              flush=True, file=sys.stderr)


def _handle_sorryax_at_root(conn, workspace: Path, problem: str) -> None:
    """Root axiom probe detected sorryAx. Bisect to find which
    non-leaf strategy leaked it, rollback the cascade chain from
    there. Framework cascade machinery will re-Backward the goal
    on the next dispatcher tick."""
    from . import verify as _verify
    culprit = _verify.bisect_sorryax_source(conn, workspace, problem)
    if culprit is None:
        print(f"[library] {problem}: sorryAx detected at root but bisect "
              f"found no source — manual investigation required",
              flush=True, file=sys.stderr)
        return
    rolled = _verify.rollback_cascade_chain(
        conn, workspace, int(culprit["id"]))
    print(f"[library] {problem}: rolled back {rolled} strategy/goal pair(s)"
          f" after sorryAx in strategy={culprit['id']}"
          f" (goal {culprit['goal_slug']})",
          flush=True)
